// @ts-check
// @ts-ignore - generated by Nuxt at build time
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt({
    rules: {
        '@typescript-eslint/no-explicit-any': 'off'
    }
});
